packages:
  - name: schedule-as-ical
    actions:
      - name: livecalendar
        main: "index.js"
        runtime: "nodejs:18"
        web: true
        environment:
          SHARE_URL: "${SHARE_URL}"
